name: "Multievent pipeline / workflow"

on:
    push:
        branches:
        - main
        - test
    pull_request:
        branches:
            main
        types:
            - closed
    workflow_dispatch:    

jobs:
    on-push: #job name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest

        steps:
            - name: "Running on master push"
              run: echo "Running on master push"
    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"
    on-pull-request-closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request closed"
              run: echo "Running on pull request closed"

    on-workflow-dispatched:
        if: github.event_name == 'workflow_dispatched'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on workflow dispatched"
              run: echo "Running on workflow dispatched"